apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agent-service
  template:
    metadata:
      labels:
        app: agent-service
    spec:
      containers:
      - name: agent-service
        image: 746669237435.dkr.ecr.ap-southeast-1.amazonaws.com/agent-service/agent-service:latest
        ports:
        - containerPort: 5000