apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: moon-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: 051826694408.dkr.ecr.ap-southeast-1.amazonaws.com/notification-service:latest
        ports:
        - containerPort: 8080
