apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-service
  namespace: moon-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracker-service
  template:
    metadata:
      labels:
        app: tracker-service
    spec:
      containers:
      - name: tracker-service
        image: 051826694408.dkr.ecr.ap-southeast-1.amazonaws.com/tracker-service:latest
        ports:
        - containerPort: 8080
