apiVersion: v1
kind: Service
metadata:
  name: tracker-service
  namespace: moon-agent
spec:
  selector:
    app: tracker-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP